Update helm-validations.yml

diff --git a/.github/workflows/helm-validations.yml b/.github/workflows/helm-validations.yml
--- a/.github/workflows/helm-validations.yml
+++ b/.github/workflows/helm-validations.yml
@@ -20,7 +20,6 @@ jobs:
     name: CSM Chart Linter
     runs-on: ubuntu-latest
     steps:
-      # Check out the repo
       - name: Checkout
         uses: actions/checkout@v6
         with:
@@ -48,5 +47,54 @@ jobs:
           fi
 
       - name: Run chart-testing linter
-        if: steps.modified-charts.outputs.modified == 'true'
+        if: ${{ steps.modified-charts.outputs.modified == 'true' }}
         run: ct lint --config ct.yaml
+
+  lint-images:
+    name: Lint CSM images
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+        with:
+          fetch-depth: "0"
+
+      - name: Get changes files
+        id: changed-files
+        run: |
+          echo "files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | tr '\n' ' ')" >> $GITHUB_OUTPUT
+
+      - name: Lint image tags
+        run: |
+          FAIL=0
+          CHANGED_FILES=${{ steps.changed-files.outputs.files }}
+
+          for file in $CHANGED_FILES; do
+            if [[ ! -f "$file" ]]; then
+              echo "ERROR: File '$file' does not exist."
+              exit 1
+            fi
+            
+            echo "Checking $file"
+
+            # Extract image references
+            IMAGES=$(grep -Eo '(image: *|FROM )[a-zA-Z0-9\./_-]+:[a-zA-Z0-9\._-]+' "$file" || true)
+            for image in $IMAGES; do
+              TAG="${image##*:}"
+              
+              # Check if it looks like a semver (e.g. 1.0.0, 2.3.4)
+              if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
+                if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
+                  echo "ERROR: Invalid tag in $file: $image"
+                  FAIL=1
+                fi
+              fi
+            done
+          done
+
+          if [ "$FAIL" -ne 0 ]; then
+            echo "Image tag linting failed"
+            exit 1
+          fi
+          
+          echo "✅ Image tag linting passed"
